### ISSUE TITLE
Error with Python 2.7.13

### ISSUE THREAD

**Issue by ggros** [kodonnell/powerbi-vcs#1]
cannot run the script with python 2.7.13
Also tested with python 3.6.2.

Traceback (most recent call last):
  File "pbivcs.py", line 123, in <module>
    if args['extract']:
TypeError: 'Namespace' object has no attribute '__getitem__'

**Comment by kodonnell** [comment]
Sorry, haven't got to supporting python 2.*. Otherwise, yes, a definite bug when I was adding that in argparse - fixed (I hope) with https://github.com/kodonnell/powerbi-vcs/commit/4c3e57d39859768516da18759d20cab574bc34cc. Does that work for you?

**Comment by ggros** [comment]
Note that I had an error in Python 3.6.2 too. The error was:
```
Traceback (most recent call last):
  File "powerbi-vcs-master\pbivcs.py", line 123, in <module>
    if args['extract']:
TypeError: 'Namespace' object is not subscriptable
```
Now the error is gone in Python 3.6.2 and the extraction did work.

**Comment by ggros** [comment]
In python 2.7.13, the error is now:
```
Traceback (most recent call last):
  File "pbivcs.py", line 124, in <module>
    extract_pbit(args.input, args.output)
  File "pbivcs.py", line 61, in extract_pbit
    conv.write_raw_to_vcs(zd.read(name), outpath)
  File "\powerbi-vcs-master\converters.py", line 21, in write_raw_to_vcs
    os.makedirs(os.path.dirname(vcspath), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```
Though if you only support Python 3 it is ok.
I saw you changed the readme accordingly, so I will close the issue.

**Comment by kodonnell** [comment]
Thanks @ggros - feel free to fire through a PR for python 2.7 support = )
