### ISSUE TITLE
Any Idea where / How Bookmarks deserialize?

### ISSUE THREAD

**Issue by kimzander1** [kodonnell/powerbi-vcs#5]
Hey Amazing work, Having fun. Any idea where bookmarks are in the vcs output??
I can't seem to find them, likely I'm doing something wrong...but I'm not finding them. Seems this might be by design, as  a TODO was to check the complement of files.  Just guessing.

**Comment by kodonnell** [comment]
No idea I'm afraid, but you could try the tool to do it:

1. create a dummy pbit, and extract it somewhere
2. add a bookmark to the pbit, and extract it somewhere else
3. compare the two extractions (with e.g. `git diff`) - hopefully only one file will have changed, and you'll see what it was.

Report back if you figure it out.

**Comment by kimzander1** [comment]
Hey! **Happy New Year!**  Yes, absolutely.  Looking fwd to trying that, now.  
But, it still eerie and inxplicable bc that, scenario is essentially what i have. (but the pbit isn't empty)  and git's not detecting changes **as expected**.  

**Detail:**
I  wasn't seeing chg's btwn updates of the same folder using (-x --overwrite) where ~15 bookmarks were added (in batches of updates), and checking git, again.  It's got me believing in something magic is going on. Again, it maybe something I'm doing.

**Comment by kodonnell** [comment]
Hmm, it works for me:

![image](https://user-images.githubusercontent.com/8204904/34466456-90f9c0a8-ef38-11e7-9310-5226085397c7.png)

Closing this - feel free to reopen if you still have problems.

**Comment by kimzander1** [comment]
..beautiful. thx kris.
